
if ((typeof LinkedInLink === "undefined" || LinkedInLink === null || LinkedInLink === "") &&
    (typeof InstagramLink === "undefined" || InstagramLink === null || InstagramLink === "") &&
    (typeof WhatsAppLink === "undefined" || WhatsAppLink === null || WhatsAppLink === "") &&
    (typeof ScheduleMeetingLink === "undefined" || ScheduleMeetingLink === null || ScheduleMeetingLink === "") &&
    (typeof CompanyLink === "undefined" || CompanyLink === null || CompanyLink === "")) {
    return false;
}
return true;